// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiR1NOGAiRaxm4Ugvucl5tHJWmINhmO9A',
    appId: '1:234895274446:web:e7dfc8d5f9b96fdb57bb9f',
    messagingSenderId: '234895274446',
    projectId: 'regenappdata',
    authDomain: 'regenappdata.firebaseapp.com',
    storageBucket: 'regenappdata.firebasestorage.app',
    measurementId: 'G-LVE6HZVGSX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqmR8hzc5Roi_m3pr3EM1lk5mPmhL41Qw',
    appId: '1:234895274446:android:7411cd89fb21aac157bb9f',
    messagingSenderId: '234895274446',
    projectId: 'regenappdata',
    storageBucket: 'regenappdata.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkCpJQytcPVqJHBszv5yhfJwuKJTzaFGE',
    appId: '1:234895274446:ios:4850205750b1b22d57bb9f',
    messagingSenderId: '234895274446',
    projectId: 'regenappdata',
    storageBucket: 'regenappdata.firebasestorage.app',
    iosBundleId: 'dev.weaponboy.regendataapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkCpJQytcPVqJHBszv5yhfJwuKJTzaFGE',
    appId: '1:234895274446:ios:4850205750b1b22d57bb9f',
    messagingSenderId: '234895274446',
    projectId: 'regenappdata',
    storageBucket: 'regenappdata.firebasestorage.app',
    iosBundleId: 'dev.weaponboy.regendataapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiR1NOGAiRaxm4Ugvucl5tHJWmINhmO9A',
    appId: '1:234895274446:web:0e5fc6c821e556e757bb9f',
    messagingSenderId: '234895274446',
    projectId: 'regenappdata',
    authDomain: 'regenappdata.firebaseapp.com',
    storageBucket: 'regenappdata.firebasestorage.app',
    measurementId: 'G-8DFMBED7DP',
  );
}
